name: "Delete Turso Database"

description: "Automatically delete a Turso database"

inputs:
  organization_name:
    description: "The name of the organization or account where this action will be performed."
    required: true
  api_token:
    description: "The API key that has access to the organization or account."
    required: true
  group_name:
    description: "The group name the database is in."
    required: false

runs:
  using: "composite"
  steps:
    - name: Get Group
      id: get-group
      if: inputs.group_name == ''
      shell: bash
      run: |
        RESPONSE=$(curl -s -f \
          -H "Authorization: Bearer ${{ inputs.api_token }}" \
          "https://api.turso.tech/v1/organizations/${{ inputs.organization_name }}/databases/${{ inputs.existing_database_name }}")

        if [ $? -ne 0 ]; then
          echo "Could not fetch database"
          exit 1
        fi

        GROUP_NAME=$(echo $RESPONSE | jq -r '.database.group')
        if [ -z "$GROUP_NAME" ]; then
          echo "Group name not found in response"
          exit 1
        fi

        echo "GROUP_NAME=$GROUP_NAME" >> $GITHUB_ENV
    - name: Delete Database
      id: delete-database
      shell: bash
      run: |
        if [ -z "${{ inputs.group_name }}" ]; then
          GROUP_TO_USE=$GROUP_NAME
        else
          GROUP_TO_USE="${{ inputs.group_name }}"
        fi

        RESPONSE=$(curl -s -f -X DELETE \
          -H "Authorization: Bearer ${{ inputs.api_token }}" \
          -H "Content-Type: application/json" \
          "https://api.turso.tech/v1/organizations/${{ inputs.organization_name }}/databases/${{ github.ref_name }}")

        if [ $? -ne 0 ]; then
          echo "Could not delete database"
          exit 1
        fi

